api_active: 3
# 0: không dùng API Google, 1: dùng API Google, 2: dùng API FPT; 3: API VIETTEL
api_darksky: c457d056f60c2aa93fd47339aadxxxx
toado: 
- 11.555358
- 106.172483
api_fpt:
- #Tạo tại fpt.ai
- #Tạo thêm acc nữa tại fpt.ai
- # Tạo thêm acc thứ 3, để vượt giới hạn 
domain: http://192.168.1.246:8123
google_application_credentials: bot.json
hass_password: pass
hotword: jarvis,jarvis,subex
led_do: 15
led_xanh: 14
longlived-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9..YDPi91PO48JSzD1lXuUv3gCA-OVASrvsdeNqJxR3iQw
model:
- jarvis.umdl
- subex.umdl
reminder: 0
sensitivity:
- 0.7
- 0.7
- 0.8
stand_alone: 0
tts: google
version_above084: right
voice: leminh
token: #Lấy tại vtcc.ai
seed: 1
spotify: 1
spotify_username: #Cần account preminum
spotify_client_id: 0e67ffbab4d446389551b5f9752f1045
spotify_client_secret: 973dd723e8d044f68e410eb8de29dced
