api_active: 1
api_darksky: null
api_fpt: null
tts: google
domain: abc

google_application_credentials: botallis.json
hass_password: pass
hotword: jarvis
led_do: 15
led_xanh: 14
longlived-token: abc
model: jarvis.umdl
reminder: 1
sensitivity:
- 0.8
- 0.8
version_above084: right
voice: male
